# Puissance 4 

In [1]:
import random
import numpy as np

## Définir une grille 6 lignes, 7 colonnes

In [27]:
def gen_grid():
    grid = np.zeros((6, 7), dtype="int32")
    return grid

In [28]:
grid = gen_grid()

In [29]:
grid

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]], dtype=int32)

In [32]:
def play(grid, col, symbol):
    if grid[0, col] != 0:
        print('Column is full!')
        return None
    
    line = 5
    while grid[line, col] != 0:
        line -= 1
    # put the symbol
    grid[line, col] = symbol
    return True
    

In [34]:
play(grid, col=2, symbol = 8)

grid

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 0, 0, 0, 0],
       [0, 0, 8, 0, 0, 0, 0],
       [0, 0, 8, 0, 0, 0, 0]], dtype=int32)

In [57]:
def check_strip(array, length):
    for end in range(3,length):
        arr = array[end-3: end]
        if np.all(arr == arr[0]) and arr[0] != 0:
            return True
    return False

In [54]:
col = grid[:,1]
col

array([0, 0, 0, 1, 1, 1], dtype=int32)

In [58]:
def check_win(grid):
    # check horizontal (lines)
    for line in grid:
        win = check_strip(line, 7)
        if win:
            return True
    # check vertical (columns)
    for col in grid.T:
        win = check_strip(col, 6)
        if win:
            return True
    return False
    

In [67]:
grid = gen_grid()

In [68]:
play(grid=grid, col=3, symbol=1)
grid

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0]], dtype=int32)

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [1, 1, 1, 8, 8, 8],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 1, 1]], dtype=int32)

In [69]:
print(check_win(grid))

False
